FROM python:3.13-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project

COPY api/ ./api/
COPY .env.example .env

EXPOSE 8000
CMD ["uv", "run", "uvicorn", "api.main:app", "--host", "::", "--port", "8000"]
